# Generated by Django 4.0.4 on 2022-11-18 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_user_created_at_user_updated_at_purchasebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_pub',
            field=models.DateField(default=datetime.datetime(2022, 11, 18, 21, 43, 33, 226353, tzinfo=utc)),
        ),
    ]
