# Generated by Django 4.0.4 on 2022-11-18 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_date_of_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_pub',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
